### ISSUE TITLE
Is there a pre training model？

### ISSUE THREAD

**Issue by dongchaoqun95** [ToyotaResearchInstitute/RemotePPG#1]
Hi all,
I want to run your models to test , but I don't see any pre-trained model, How I can access to them?

**Comment by JohnGideon-TRI** [comment]
No. Since the numbers we report in our paper used multiple runs, so the total number of models trained exceeds several hundred, we are not planning to release these models. However, the code here should allow you to reproduce any particular model of interest fairly quickly. Let us know if you run into any issues.
